# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/grocery_store_db
spring.datasource.username=postgres
spring.datasource.password=R05k072005@$
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JOOQ
spring.jooq.sql-dialect=postgres